In [ ]:
import numpy as np

# 1. Array Thinking vs. Iteration
Traditional iterative approach uses explicit Python loops. It is slow because each iteration involves Python overhead.

Array thinking treats data as whole arrays and applies operations directly, leveraging fast compiled code.

In [ ]:
# Traditional Python loop
def square_python(numbers):
    result = []
    for x in numbers:
        result.append(x ** 2)
    return result

# NumPy array thinking
def square_numpy(arr):
    return arr ** 2

In [ ]:
nums = list(range(11))
print(square_python(nums))
print(square_numpy(np.array(nums)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[  0   1   4   9  16  25  36  49  64  81 100]


# 2.Vectorization
Vectorization is the process of replacing explicit loops with array‑level operations. NumPy’s vectorized functions run in C, making them much faster.

In [ ]:
# Example: element-wise multiplication of two large arrays
size = 10_000_000
a = np.random.rand(size)
b = np.random.rand(size)

# Vectorized multiplication
%timeit c = a * b

30.8 ms ± 473 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# 3. Broadcasting
Broadcasting allows operations on arrays of different shapes without making copies of data.

In [ ]:
# Add a 1D array to each row of a 2D array
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
row_bias = np.array([10, 20, 30])

result = matrix + row_bias  # broadcasting happens automatically
print(result)


[[11 22 33]
 [14 25 36]]


# 4. Memory Efficiency
NumPy stores data in contiguous memory blocks, uses strides, and provides views instead of copies whenever possible.

In [ ]:
arr = np.arange(1_000_000)

# A slice returns a view (no data copy)
view = arr[::2]
print(view.base is arr)   # True, view shares memory with arr


True


In [ ]:
# Reshape usually returns a view (if possible)
reshaped = arr.reshape(500_000, 2)
print(reshaped.base is arr)   # True

True


In [ ]:
# Explicit copy if needed
copy = arr.copy()
print(copy.base is arr)

False


Strides allow efficient transposition without moving data:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.strides)

(24, 8)


In [ ]:
transposed = arr.T
print(transposed.strides)

(8, 24)


# 5. Universal Functions (ufuncs)
Ufuncs are fast, element‑wise functions that support broadcasting, type casting, and optional output arrays.

In [ ]:
arr = np.array([1, 2, 3])

print(np.exp(arr))          # exponential
print(np.log(arr))          # natural log
print(np.greater(arr, 2))   # comparison ufunc


result = np.empty_like(arr)
np.multiply(arr, 10, out=result)   # writes directly into 'result'
print(result)

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[False False  True]
[10 20 30]


# 6. Performance Comparison: Python Loop vs. NumPy
We will create a list/array of 4 million numbers and square each element. We measure:

In [ ]:
import time
import tracemalloc

# Number of elements
N = 4_000_000

# ---- Python list approach ----
print("Python list approach:")
data_py = list(range(N))

tracemalloc.start()
start_time = time.perf_counter()

squared_py = [x**2 for x in data_py]

end_time = time.perf_counter()
current, peak = tracemalloc.get_traced_memory()
tracemalloc.stop()

print(f"  Time: {end_time - start_time:.4f} seconds")
print(f"  Peak memory: {peak / 1024**2:.2f} MB")
print(f"  Result size: {len(squared_py)} elements")


Python list approach:
  Time: 5.5261 seconds
  Peak memory: 155.20 MB
  Result size: 4000000 elements


In [ ]:
# ---- NumPy array approach ----
print("\nNumPy array approach:")
data_np = np.arange(N, dtype=np.int64)   # use int64 to match Python int size

tracemalloc.start()
start_time = time.perf_counter()

squared_np = data_np ** 2

end_time = time.perf_counter()
current, peak = tracemalloc.get_traced_memory()
tracemalloc.stop()

print(f"  Time: {end_time - start_time:.4f} seconds")
print(f"  Peak memory: {peak / 1024**2:.2f} MB")
print(f"  Result shape: {squared_np.shape}")


NumPy array approach:
  Time: 0.0068 seconds
  Peak memory: 30.54 MB
  Result shape: (4000000,)


# performance ratio

In [ ]:
5.5261 / 0.0068 # 812 times faster

812.6617647058823

numpy is far faster than pyhton base loops

# peak memory utilization ratio

In [ ]:
155.20 / 30.54

5.081859855926654

numpy uses apporax 5 times less peak memory